create database PTTK
use PTTK
set dateformat DMY
create table Account1(accountID INT NOT NULL IDENTITY(1,1) , accountName nvarchar(25), password nvarchar(25), fullName nvarchar(225), birthday date, Email nvarchar(60), phoneNumber nvarchar(12));
/*
drop table Account1;
drop table Account;
create table Account(accountID varchar(500) not null primary key, accountName nvarchar(25), password nvarchar(25), fullName nvarchar(225), birthday date, Email nvarchar(60), phoneNumber nvarchar(12));

create table BusRoute( routeID int primary key, unitID nvarchar(10), routeName nvarchar(225), timeStart nvarchar(40), timeEnd nvarchar(40) , timeBreak DECIMAL(5,3), startLocation nvarchar(225), endLocation nvarchar(225), kindRoute nvarchar(225))

create table BusUnitManager( unitID nvarchar(10) primary key, unitName nvarchar(225), phoneNumber nvarchar(12), Email nvarchar(60))

create table Driver( driverID nvarchar(10) primary key, fullName nvarchar(225), birthday date, male bit, address nvarchar(225), country nvarchar(225), dayBegin date, salary INT, driverLicense nvarchar(10), BusID nvarchar(10))

create table Bus( BusID  nvarchar(10) primary key, licensePlate nvarchar(40), kind nvarchar(225), manufactureDay date, lateGuaranteeDay date, routeID int)

create table Chuyen(MaTuyen int, STT int, TenTram nvarchar(225))

create table BusStop( routeID int, serial int, nameBusStop nvarchar(225))
*/
-- table Account
insert into Account values('6','khanh','khanh',N'Quốc Khánh','2000-06-15','b@gmail.com','1234556');
-- table Chuyen
/*
insert into Chuyen values(19, 1,N'Bến xe buýt Sài Gòn')
insert into Chuyen values(19, 2,N'Tôn Thất Tùng')
insert into Chuyen values(19, 3,N'Nguyễn Thị Nghĩa')
insert into Chuyen values(19, 4,N'Trường Emst Thalmann')
insert into Chuyen values(19, 5,N'Trạm Trung chuyển trên đường Hàm Nghi')
insert into Chuyen values(19, 6,N'Nam Kỳ Khởi Nghĩa')
insert into Chuyen values(19, 7,N'Chợ Cũ')
insert into Chuyen values(19, 8,N'Hồ Tùng Mậu')
insert into Chuyen values(19, 9,N'Bến Bạch Đằng')
insert into Chuyen values(19, 10,N'Công Trường Mê Linh')
insert into Chuyen values(19, 11,N'Nhà Hát Thành Phố')
insert into Chuyen values(19, 12,N'Bệnh viện Nhi Đồng 2')
insert into Chuyen values(19, 13,N'Bưu Điện Thành Phố')
insert into Chuyen values(19, 14,N'Khách sạn Sofitel')
insert into Chuyen values(19, 15,N'Đại học Khoa học xã hội nhân văn')
insert into Chuyen values(19, 16,N'Thảo Cầm Viên')
insert into Chuyen values(19, 17,N'Cầu Thị Nghè')
insert into Chuyen values(19, 18,N'Nhà Thờ Thị Nghè')
insert into Chuyen values(19, 19,N'Trung tâm Dưỡng Lão')
insert into Chuyen values(19, 20,N'Trường trung học Gia Định')
insert into Chuyen values(19, 21,N'Ngã Ba Hàng Xanh')
insert into Chuyen values(19, 22,N'Đài Liệt sĩ')
insert into Chuyen values(19, 23,N'Siêu thị Coop Mart')
insert into Chuyen values(19, 24,N'Bến xe Miền Đông')
insert into Chuyen values(19, 25,N'Trường TH Bình Triệu')
insert into Chuyen values(19, 26,N'Trạm xăng dầu')
insert into Chuyen values(19, 27,N'Cầu Ông Dầu')
insert into Chuyen values(19, 28,N'Đường số 3')
insert into Chuyen values(19, 29,N'Đường số 4')
insert into Chuyen values(19, 30, N'Cân Nhơn Hòa')
insert into Chuyen values(19, 31, N'Ngã 3 Hiệp Bình')
insert into Chuyen values(19, 32, N'Ngã 3 Đường Hiệp Bình')
insert into Chuyen values(19, 33, N'Trạm y tế Hiệp Bình Phước')
insert into Chuyen values(19, 34, N'UBND P.Hiệp Bình Phước')
insert into Chuyen values(19, 35, N'Hồ Bơi')
insert into Chuyen values(19, 36, N'Ngã 4 Bình Phước')
insert into Chuyen values(19, 37, N'Ngã ba mũi tàu đường Gò Dưa')
insert into Chuyen values(19, 38, N'Chợ Đầu Mối')
insert into Chuyen values(19, 39, N'Chợ Tam Bình')
insert into Chuyen values(19, 40, N'Hồ Bơi')
insert into Chuyen values(19, 41, N'Chợ Tam Hải')
insert into Chuyen values(19, 42, N'Cầu vượt Sóng Thần')
insert into Chuyen values(19, 43, N'Bến xe Lam Hồng')
insert into Chuyen values(19, 44, N'Giày da Thái Bình')
insert into Chuyen values(19, 45, N'Cầu vượt Linh Xuân')
insert into Chuyen values(19, 46, N'Vietcombank')
insert into Chuyen values(19, 47, N'Nghĩa trang TP')
insert into Chuyen values(19, 48, N'ĐH Kinh tế Luật')
insert into Chuyen values(19, 49, N'Công ty điện tử Samsung')
insert into Chuyen values(19, 50, N'Đại học Nông Lâm')
insert into Chuyen values(19, 51, N'Đại học Nông Lâm')
insert into Chuyen values(19, 52, N'Cầu Vượt Trạm 2')
insert into Chuyen values(19, 53, N'Suối Tiên')
insert into Chuyen values(19, 54, N'Vành đại ĐHQG TPHCM')
insert into Chuyen values(19, 55, N'KTX Khu A ĐH Quốc Gia TPHCM')
insert into Chuyen values(19, 56, N'Đại học Quốc tế')
insert into Chuyen values(19, 57, N'Nhà văn hoá sinh viên')
insert into Chuyen values(19, 58, N'Đại học Quốc gia')

--19 back
insert into Chuyen values(-19, 1, N'Đại học Quốc gia')
insert into Chuyen values(-19, 2, N'Nhà Văn hoá sinh viên')
insert into Chuyen values(-19, 3, N'Đại học Quốc tế')
insert into Chuyen values(-19, 4, N'KTX Khu A ĐH Quốc Gia TPHCM')
insert into Chuyen values(-19, 5, N'Suối Tiên')
insert into Chuyen values(-19, 6, N'Thảo Nguyên')
insert into Chuyen values(-19, 7, N'Đại học Nông Lâm')
insert into Chuyen values(-19, 8, N'Đại học Nông Lâm')
insert into Chuyen values(-19, 9, N'Công ty điện tử Samsung')
insert into Chuyen values(-19, 10, N'Đại học Kinh tế -Luật')
insert into Chuyen values(-19, 11, N'Trung tâm kho vận Linh Xuân')
insert into Chuyen values(-19, 12, N'Nghĩa trang Thành phố')
insert into Chuyen values(-19, 13, N'Công ty Nissan')
insert into Chuyen values(-19, 14, N'Cầu vượt Linh Xuân')
insert into Chuyen values(-19, 15, N'Giày Thái Bình-Bình Đường')
insert into Chuyen values(-19, 16, N'Giày Thái Bình')
insert into Chuyen values(-19, 17, N'Bến xe Lam Hồng')
insert into Chuyen values(-19, 18, N'Cầu vượt Sóng Thần')
insert into Chuyen values(-19, 19, N'Chợ Tam Hải')
insert into Chuyen values(-19, 20, N'Hồ Bơi')
insert into Chuyen values(-19, 21, N'Chợ Tam Bình')
insert into Chuyen values(-19, 22, N'Chợ đầu mối nông sản Thủ Đức')
insert into Chuyen values(-19, 23, N'Ngã 4 Bình Phước')
insert into Chuyen values(-19, 24, N'Hồ bơi Mèo Mun')
insert into Chuyen values(-19, 25, N'UBND P.Hiệp Bình Phước')
insert into Chuyen values(-19, 26, N'Trạm y tế P. Hiệp Bình Phước')
insert into Chuyen values(-19, 27, N'Ngã 3 Đường Hiệp Bình')
insert into Chuyen values(-19, 28, N'Ngã 3 Hiệp Bình')
insert into Chuyen values(-19, 29, N'Cân Nhơn Hòa')
insert into Chuyen values(-19, 30, N'Đường số 4')
insert into Chuyen values(-19, 31, N'Đường số 3')
insert into Chuyen values(-19, 32, N'Cầu Ông Dầu')
insert into Chuyen values(-19, 33, N'Trạm xăng dầu')
insert into Chuyen values(-19, 34, N'UBND P.Hiệp Bình Chánh')
insert into Chuyen values(-19, 35, N'Cổng vào-Bến xe Miền Đông')
insert into Chuyen values(-19, 36, N'Ngã năm Liệt Sĩ')
insert into Chuyen values(-19, 37, N'Chợ Phường 25')
insert into Chuyen values(-19, 38, N'Đại học Ngoại Thương')
insert into Chuyen values(-19, 39, N'Trường ĐH Giao thông Vận tải Tp. HCM')
insert into Chuyen values(-19, 40, N'Đại học Hutech')
insert into Chuyen values(-19, 41, N'Cây xăng dầu')
insert into Chuyen values(-19, 42, N'Trường trung học Gia Định')
insert into Chuyen values(-19, 43, N'Trường Tiểu học Hồng Hà')
insert into Chuyen values(-19, 44, N'Ngã ba Nguyễn Cửu Vân')
insert into Chuyen values(-19, 45, N'Nhà thờ Thị Nghè')
insert into Chuyen values(-19, 46, N'Thảo Cầm Viên')
insert into Chuyen values(-19, 47, N'Đài truyền hình')
insert into Chuyen values(-19, 48, N'Đại học Y Dược')
insert into Chuyen values(-19, 49, N'Khách sạn Sofitel')
insert into Chuyen values(-19, 50, N'Bệnh viện Nhi Đồng 2')
insert into Chuyen values(-19, 51, N'Nhà Hát Thành Phố')
insert into Chuyen values(-19, 52, N'Công Trường Mê Linh')
insert into Chuyen values(-19, 53, N'Bến Bạch Đằng')
insert into Chuyen values(-19, 54, N'Cục Hải Quan Thành Phố')
insert into Chuyen values(-19, 55, N'Chợ Cũ')
insert into Chuyen values(-19, 56, N'Trường Cao Thắng')
insert into Chuyen values(-19, 57, N'Trạm Trung chuyển trên đường Hàm Nghi')
insert into Chuyen values(-19, 58, N'Khách sạn New World')
insert into Chuyen values(-19, 59, N'Nguyễn Thị Nghĩa')
insert into Chuyen values(-19, 60, N'Tôn Thất Tùng')
insert into Chuyen values(-19, 61, N'Bến xe buýt Sài Gòn')
---32 back
insert into Chuyen values(-32, 1, N'Bến xe Ngã tư Ga')
insert into Chuyen values(-32, 2, N'Ngã tư Ga')
insert into Chuyen values(-32, 3, N'Nhà hàng Bến Xưa')
insert into Chuyen values(-32, 4, N'Cầu An Lộc')
insert into Chuyen values(-32, 5, N'Bến Đò')
insert into Chuyen values(-32, 6, N'Bưu điện An Nhơn')
insert into Chuyen values(-32, 7, N'Ngã tư An Nhơn')
insert into Chuyen values(-32, 8, N'Bệnh Viện Gò Vấp')
insert into Chuyen values(-32, 9, N'Trường THCS Lý Tự Trọng')
insert into Chuyen values(-32, 10, N'Nhà thờ Trung Bắc')
insert into Chuyen values(-32, 11, N'Nhà Thờ Hà Nội')
insert into Chuyen values(-32, 12, N'Nhà thờ Hợp An')
insert into Chuyen values(-32, 13, N'Trường Lê Thị Hồng Gấm')
insert into Chuyen values(-32, 14, N'Trung tâm Văn hóa Quận Gò Vấp')
insert into Chuyen values(-32, 15, N'Nhà thờ Thạch Đà')
insert into Chuyen values(-32, 16, N'Chợ Thạch Đà')
insert into Chuyen values(-32, 17, N'Công ty Huê Phong')
insert into Chuyen values(-32, 18, N'Đường số 53')
insert into Chuyen values(-32, 19, N'Ngã ba Cây Trâm')
insert into Chuyen values(-32, 20, N'Trường An Hội')
insert into Chuyen values(-32, 21, N'Ngã ba Nguyễn Duy Cung')
insert into Chuyen values(-32, 22, N'Chùa Linh Sơn Hải Hội')
insert into Chuyen values(-32, 23, N'Nhà sách Phan Huy Ích')
insert into Chuyen values(-32, 24, N'Trung tâm Y khoa Dân Sinh')
insert into Chuyen values(-32, 25, N'Trường Cao đẳng Du Lịch')
insert into Chuyen values(-32, 26, N'Nhà máy hóa chất Tân Bình')
insert into Chuyen values(-32, 27, N'Nhà thờ Hy Vọng')
insert into Chuyen values(-32, 28, N'Cao ốc Phúc Yên')
insert into Chuyen values(-32, 29, N'Trạm Dệt Thành Công')
insert into Chuyen values(-32, 30, N'Cổng Khu công nghiệp Tân Bình')
insert into Chuyen values(-32, 31, N'Cây xăng Tây Thạnh')
insert into Chuyen values(-32, 32, N'Trạm đầu D9')
insert into Chuyen values(-32, 33, N'Trạm cuối D9')
insert into Chuyen values(-32, 34, N'Trung tâm Văn Hóa Quận Tân Phú')
insert into Chuyen values(-32, 35, N'Lê Trọng Tấn')
insert into Chuyen values(-32, 36, N'Trường Đại học Công Nghiệp Thực Phẩm')
insert into Chuyen values(-32, 37, N'Trạm Đầu Lê Trọng Tấn')
insert into Chuyen values(-32, 38, N'Trạm café BonJour')
insert into Chuyen values(-32, 39, N'Trạm Đường Số 27')
insert into Chuyen values(-32, 40, N'Trạm cây xăng Sài Gòn Petro')
insert into Chuyen values(-32, 41, N'Showroom otô')
insert into Chuyen values(-32, 42, N'Trạm Nhà Thờ Họ Tộc Nguyễn')
insert into Chuyen values(-32, 43, N'Trạm Đầu Tân Quý')
insert into Chuyen values(-32, 44, N'Trạm UB phường Tân Quý')
insert into Chuyen values(-32, 45, N'Trạm Gò Dầu')
insert into Chuyen values(-32, 46, N'Tiệm cửa sắt')
insert into Chuyen values(-32, 47, N'Trạm Y tế phường Tân Quý')
insert into Chuyen values(-32, 48, N'Trạm Chợ Tân Hương')
insert into Chuyen values(-32, 49, N'Trường GTVT')
insert into Chuyen values(-32, 50, N'Phạm Văn Xảo')
insert into Chuyen values(-32, 51, N'Chợ Phường 18')
insert into Chuyen values(-32, 52, N'Trần Thủ Độ')
insert into Chuyen values(-32, 53, N'Lê Cao Lãng')
insert into Chuyen values(-32, 54, N'Cuối Tô Hiệu')
insert into Chuyen values(-32, 55, N'Đầu Tô Hiệu')
insert into Chuyen values(-32, 56, N'Trâm Tâm Mua Sắm')
insert into Chuyen values(-32, 57, N'Trung Tâm Anh Ngữ')
insert into Chuyen values(-32, 58, N'Trạm Xưởng May Việt Đại')
insert into Chuyen values(-32, 59, N'Công ty Dệt May Sài Gòn')
insert into Chuyen values(-32, 60, N'Cầu Tân Hóa')
insert into Chuyen values(-32, 61, N'Cầu Ông Buông')
insert into Chuyen values(-32, 62, N'Cầu Ông Buông')
insert into Chuyen values(-32, 63, N'Vòng xoay Phú Lâm')
insert into Chuyen values(-32, 64, N'Cư Xá Phú Lâm')
insert into Chuyen values(-32, 65, N'Hồ Bơi Phú Lâm')
insert into Chuyen values(-32, 66, N'Công Viên Phú Lâm')
insert into Chuyen values(-32, 67, N'Vòng xoay Kinh Dương Vương')
insert into Chuyen values(-32, 68, N'Bến xe Miền Tây')
insert into Chuyen values(-32, 69, N'Bến xe Miền Tây')
---32 go
insert into Chuyen values(32, 1,N'Bến xe Miền Tây')
insert into Chuyen values(32, 2,N'Kinh Dương Vương')
insert into Chuyen values(32, 3,N'Công viên Phú Lâm')
insert into Chuyen values(32, 4,N'Hồ Bơi Phú Lâm')
insert into Chuyen values(32, 5,N'Cư xá Phú Lâm')
insert into Chuyen values(32, 6,N'UBND Phường 13')
insert into Chuyen values(32, 7,N'Tân Hóa')
insert into Chuyen values(32, 8,N'Cầu Tân Hóa')
insert into Chuyen values(32, 9,N'Công ty Dệt May Sài Gòn')
insert into Chuyen values(32, 10,N'Công Ty bao bì nhựa Tân Tiến')
insert into Chuyen values(32, 11,N'Trung Tâm Mua Sắm')
insert into Chuyen values(32, 12,N'Đầu Tô Hiệu')
insert into Chuyen values(32, 13,N'Cuối Tô Hiệu')
insert into Chuyen values(32, 14,N'Nguyễn Lý')
insert into Chuyen values(32, 15,N'Lê Cao Lãng')
insert into Chuyen values(32, 16,N'Trần Thủ Độ')
insert into Chuyen values(32, 17,N'Chợ Phường 18')
insert into Chuyen values(32, 18,N'Phạm Văn Xảo')
insert into Chuyen values(32, 19,N'Trường GTVT')
insert into Chuyen values(32, 20,N'Trạm Chợ Tân Hương')
insert into Chuyen values(32, 21,N'Trạm y tế P.Tân Quý')
insert into Chuyen values(32, 22,N'Trạm café Minh Thùy')
insert into Chuyen values(32, 23,N'Trạm Ngã 4 Gò Dầu- Tân Quý')
insert into Chuyen values(32, 24,N'Trạm UBND Phường Tân Quý')
insert into Chuyen values(32, 25,N'Đỗ Công Tường')
insert into Chuyen values(32, 26,N'Trạm Tân Kỳ Tân Quý')
insert into Chuyen values(32, 27,N'Trạm Nhà Thờ Họ Tộc Nguyễn')
insert into Chuyen values(32, 28,N'Showroom otô')
insert into Chuyen values(32, 29,N'Trạm Xăng')
insert into Chuyen values(32, 30,N'Trạm Đường Số 27')
insert into Chuyen values(32, 31,N'Trạm Lê Trọng Tấn')
insert into Chuyen values(32, 32,N'Trạm Đầu Lê Trọng Tấn')
insert into Chuyen values(32, 33,N'Trường Đại học Công Nghiệp Thực Phẩm')
insert into Chuyen values(32, 34,N'Lê Trọng Tấn')
insert into Chuyen values(32, 35,N'Trung tâm Văn Hóa Quận Tân Phú')
insert into Chuyen values(32, 36,N'Trạm Bơm')
insert into Chuyen values(32, 37, N'Trạm cuối D9')
insert into Chuyen values(32, 38, N'Cây xăng Tây Thạnh')
insert into Chuyen values(32, 39, N'Trạm Cổng KCN Tân Bình')
insert into Chuyen values(32, 40, N'Khu Công Nghiệp Tân Bình')
insert into Chuyen values(32, 41, N'Chung cư Phúc Yên')
insert into Chuyen values(32, 42, N'Nhà thờ Hy Vọng')
insert into Chuyen values(32, 43, N'Nhà máy hóa chất Tân Bình')
insert into Chuyen values(32, 44, N'Trường Cao đẳng Du Lịch')
insert into Chuyen values(32, 45, N'Trung tâm y khoa Dân Sinh')
insert into Chuyen values(32, 46, N'Cây xăng Anh Thư')
insert into Chuyen values(32, 47, N'Nhà sách Phan Huy Ích')
insert into Chuyen values(32, 48, N'Chùa Linh Sơn Hải Hội')
insert into Chuyen values(32, 49, N'Ngã ba Nguyễn Duy Cung')
insert into Chuyen values(32, 50, N'Trường An Hội')
insert into Chuyen values(32, 51, N'Ngã Ba Cây Trâm')
insert into Chuyen values(32, 52, N'Đường số 53')
insert into Chuyen values(32, 53, N'Công ty Huê Phong')
insert into Chuyen values(32, 54, N'Chợ Thạch Đà')
insert into Chuyen values(32, 55, N'Nhà thờ Thạch Đà')
insert into Chuyen values(32, 56, N'Trung tâm Văn hóa Quận Gò Vấp')
insert into Chuyen values(32, 57, N'Trường Lê Thị Hồng Gấm')
insert into Chuyen values(32, 58, N'Nhà thờ Hợp An')
insert into Chuyen values(32, 59, N'Nhà Thờ Hà Nội')
insert into Chuyen values(32, 60, N'Nhà thờ Trung Bắc')
insert into Chuyen values(32, 61, N'Trường THCS Lý Tự Trọng')
insert into Chuyen values(32, 62, N'Bệnh Viện Gò Vấp')
insert into Chuyen values(32, 63, N'Ngã Ba Lê Hoàng Phái')
insert into Chuyen values(32, 64, N'Ngã tư An Nhơn')
insert into Chuyen values(32, 65, N'Bến Đò')
insert into Chuyen values(32, 66, N'Cầu An Lộc')
insert into Chuyen values(32, 67, N'Nhà hàng Bến Xưa')
insert into Chuyen values(32, 68, N'Ngã tư Ga')
insert into Chuyen values(32, 69, N'Ngọc Lan')
insert into Chuyen values(32, 70, N'Bến xe Ngã tư Ga')
---33 back
insert into Chuyen values(-33, 1, N'Bến Xe Buýt ÐH Quốc Gia')
insert into Chuyen values(-33, 2, N'KTX Khu B ĐHQG')
insert into Chuyen values(-33, 3, N'Viện Tài nguyên môi trường')
insert into Chuyen values(-33, 4, N'Nhà khách ĐHQG')
insert into Chuyen values(-33, 5, N'Hồ Đá')
insert into Chuyen values(-33, 6, N'Đại học Quốc tế')
insert into Chuyen values(-33, 7, N'KTX Khu A ĐH Quốc Gia TPHCM')
insert into Chuyen values(-33, 8, N'Đại học An Ninh Nhân Dân')
insert into Chuyen values(-33, 9, N'Trường giáo dục Quốc phòng')
insert into Chuyen values(-33, 10, N'Khu DL Suối Tiên')
insert into Chuyen values(-33, 11, N'Suối Tiên')
insert into Chuyen values(-33, 12, N'Thảo Nguyên')
insert into Chuyen values(-33, 13, N'Đại học Nông Lâm')
insert into Chuyen values(-33, 14, N'Đại học Nông Lâm')
insert into Chuyen values(-33, 15, N'Công ty điện tử Samsung')
insert into Chuyen values(-33, 16, N'Đại học Kinh tế -Luật')
insert into Chuyen values(-33, 17, N'Trung tâm kho vận Linh Xuân')
insert into Chuyen values(-33, 18, N'Nghĩa trang Thành phố')
insert into Chuyen values(-33, 19, N'Công ty Nissan')
insert into Chuyen values(-33, 20, N'Cầu vượt Linh Xuân')
insert into Chuyen values(-33, 21, N'Giày Thái Bình-Bình Đường')
insert into Chuyen values(-33, 22, N'Giày Thái Bình')
insert into Chuyen values(-33, 23, N'Bến xe Lam Hồng')
insert into Chuyen values(-33, 24, N'Cầu vượt Sóng Thần')
insert into Chuyen values(-33, 25, N'Chợ Tam Hải')
insert into Chuyen values(-33, 26, N'Hồ Bơi')
insert into Chuyen values(-33, 27, N'Chợ Tam Bình')
insert into Chuyen values(-33, 28, N'Chợ đầu mối nông sản Thủ Đức')
insert into Chuyen values(-33, 29, N'Cầu Bình Phước')
insert into Chuyen values(-33, 30, N'Aone')
insert into Chuyen values(-33, 31, N'Công ty EUROPA')
insert into Chuyen values(-33, 32, N'Tu viện Khánh An')
insert into Chuyen values(-33, 33, N'Công ty Mai Linh')
insert into Chuyen values(-33, 34, N'Đình An Phú Đông')
insert into Chuyen values(-33, 35, N'Đài Liệt sĩ An Phú Đông')
insert into Chuyen values(-33, 36, N'Công ty Hồng Mã')
insert into Chuyen values(-33, 37, N'Phường An Phú Đông')
insert into Chuyen values(-33, 38, N'Cầu Ga Nhỏ')
insert into Chuyen values(-33, 39, N'Bến xe Ngã tư Ga')
insert into Chuyen values(-33, 40, N'Khu QLGTĐT số 3')
insert into Chuyen values(-33, 41, N'Tô Ngọc Vân')
insert into Chuyen values(-33, 42, N'Trường Mầm non Ngôi Nhà Trẻ Thơ')
insert into Chuyen values(-33, 43, N'Cơ khí Minh Huy')
insert into Chuyen values(-33, 44, N'Đá hoa cương Chí Thành')
insert into Chuyen values(-33, 45, N'Quận ủy Quận 12')
insert into Chuyen values(-33, 46, N'Tân Thới Hiệp')
insert into Chuyen values(-33, 47, N'Cao su Vina')
insert into Chuyen values(-33, 48, N'Cây xăng Trung Tín')
insert into Chuyen values(-33, 49, N'Trạm điện Hóc Môn')
insert into Chuyen values(-33, 50, N'Ngã tư Đình')
insert into Chuyen values(-33, 51, N'Nhà lầu')
insert into Chuyen values(-33, 52, N'Trường Nguyễn Du')
insert into Chuyen values(-33, 53, N'Công viên Phần mềm Quang Trung')
insert into Chuyen values(-33, 54, N'Chung cư Thái An')
insert into Chuyen values(-33, 55, N'Trạm đăng kiểm')
insert into Chuyen values(-33, 56, N'Bãi xe Tây Nam')
insert into Chuyen values(-33, 57, N'Cầu vượt An Sương')
insert into Chuyen values(-33, 58, N'Quốc lộ 22')
insert into Chuyen values(-33, 59, N'Bến xe An Sương')

---33 go
insert into Chuyen values(33, 1, N'Bến xe An Sương')
insert into Chuyen values(33, 2, N'Cầu vượt An Sương')
insert into Chuyen values(33, 3, N'Trạm đăng kiểm')
insert into Chuyen values(33, 4, N'Chung cư Thái An')
insert into Chuyen values(33, 5, N'Đài phát thanh Quán Tre')
insert into Chuyen values(33, 6, N'Trường Nguyễn Du')
insert into Chuyen values(33, 7, N'Bảo vệ Nam Long Hải')
insert into Chuyen values(33, 8, N'Ngã tư Đình')
insert into Chuyen values(33, 9, N'Cây xăng Năng lượng')
insert into Chuyen values(33, 10, N'Cao su Vina')
insert into Chuyen values(33, 11, N'Ngã tư Tân Thới Hiệp')
insert into Chuyen values(33, 12, N'UBND Quận 12')
insert into Chuyen values(33, 13, N'Bãi xe Tri Ân')
insert into Chuyen values(33, 14, N'Cầu Bến Cát')
insert into Chuyen values(33, 15, N'Gò Sao')
insert into Chuyen values(33, 16, N'Cây xăng Thạnh Xuân')
insert into Chuyen values(33, 17, N'Cầu Cả Bốn')
insert into Chuyen values(33, 18, N'Bến xe Ngã tư Ga')
insert into Chuyen values(33, 19, N'Cầu Ga nhỏ')
insert into Chuyen values(33, 20, N'An Phú Đông')
insert into Chuyen values(33, 21, N'Công ty Vĩnh Hưng')
insert into Chuyen values(33, 22, N'Đài liệt sĩ An Phú Đông')
insert into Chuyen values(33, 23, N'ĐH Nguyễn Tất Thành')
insert into Chuyen values(33, 24, N'Công ty đá Ngọc Ngân')
insert into Chuyen values(33, 25, N'Cây xăng Petrolimex 12')
insert into Chuyen values(33, 26, N'Bãi đậu xe kho hàng')
insert into Chuyen values(33, 27, N'Aone')
insert into Chuyen values(33, 28, N'Ngã 4 Bình Phước')
insert into Chuyen values(33, 29, N'Ngã ba mũi tàu đường Gò Dưa')
insert into Chuyen values(33, 30, N'Chợ Đầu Mối')
insert into Chuyen values(33, 31, N'Chợ Tam Bình')
insert into Chuyen values(33, 32, N'Hồ Bơi')
insert into Chuyen values(33, 33, N'Chợ Tam Hải')
insert into Chuyen values(33, 34, N'Cầu vượt Sóng Thần')
insert into Chuyen values(33, 35, N'Bến xe Lam Hồng')
insert into Chuyen values(33, 36, N'Giày da Thái Bình')
insert into Chuyen values(33, 37, N'Cầu vượt Linh Xuân')
insert into Chuyen values(33, 38, N'Vietcombank')
insert into Chuyen values(33, 39, N'Nghĩa trang TP')
insert into Chuyen values(33, 40, N'ĐH Kinh tế Luật')
insert into Chuyen values(33, 41, N'Công ty điện tử Samsung')
insert into Chuyen values(33, 42, N'Đại học Nông Lâm')
insert into Chuyen values(33, 43, N'Đại học Nông Lâm')
insert into Chuyen values(33, 44, N'Cầu Vượt Trạm 2')
insert into Chuyen values(33, 45, N'Suối Tiên')
insert into Chuyen values(33, 46, N'Nghĩa trang liệt sĩ TP.HCM')
insert into Chuyen values(33, 47, N'Vành đại ĐHQG TPHCM')
insert into Chuyen values(33, 48, N'KTX Khu A ĐH Quốc Gia TPHCM')
insert into Chuyen values(33, 49, N'Đại học Quốc tế')
insert into Chuyen values(33, 50, N'Hồ Đá')
insert into Chuyen values(33, 51, N'Nhà Khách ĐHQG')
insert into Chuyen values(33, 52, N'Viện Tài nguyên môi trường')
insert into Chuyen values(33, 53, N'KTX Khu B ĐHQG')
insert into Chuyen values(33, 54,N'Bến Xe Buýt ÐH Quốc Gia')
---43 back
insert into Chuyen values(-43, 1, N'Cát Lái')
insert into Chuyen values(-43, 2, N'Sân bóng đá mini')
insert into Chuyen values(-43, 3, N'Khu Dân Cư Phố Đông')
insert into Chuyen values(-43, 4, N'UBND Phường Cát Lái')
insert into Chuyen values(-43, 5, N'Chợ Cây Xoài')
insert into Chuyen values(-43, 6, N'Đường số 10')
insert into Chuyen values(-43, 7, N'Trung tâm dạy nghề quận 2')
insert into Chuyen values(-43, 8, N'Trung tâm y tế dự phòng Quận 2')
insert into Chuyen values(-43, 9, N'Trường Câp 3 Giồng Ông Tố')
insert into Chuyen values(-43, 10, N'Chùa Thái Nguyên')
insert into Chuyen values(-43, 11, N'Phòng Đào tạo Quận 2')
insert into Chuyen values(-43, 12, N'Siêu thị Chợ Lớn')
insert into Chuyen values(-43, 13, N'Cầu Ông Tranh')
insert into Chuyen values(-43, 14, N'Chùa Huệ Nghiêm')
insert into Chuyen values(-43, 15, N'Đường số 8')
insert into Chuyen values(-43, 16, N'Đình Bình Khánh')
insert into Chuyen values(-43, 17, N'Trần Não')
insert into Chuyen values(-43, 18, N'Lương Định Của')
insert into Chuyen values(-43, 19, N'Chùa Diệu Giác')
insert into Chuyen values(-43, 20, N'KTX Đại học Giao thông Vận tải')
insert into Chuyen values(-43, 21, N'Nhà Sách An Bình')
insert into Chuyen values(-43, 22, N'Đường Quốc Hương')
insert into Chuyen values(-43, 23, N'Cầu Sài Gòn')
insert into Chuyen values(-43, 24, N'Khu Du lịch Văn Thánh')
insert into Chuyen values(-43, 25, N'Đại học Hutech')
insert into Chuyen values(-43, 26, N'Cây xăng dầu')
insert into Chuyen values(-43, 27, N'Ngã Ba Hàng Xanh')
insert into Chuyen values(-43, 28, N'Siêu thị Coop Mart')
insert into Chuyen values(-43, 29, N'Cổng ra - Bến xe Miền Đông 1')
insert into Chuyen values(-43, 30, N'Cổng vào-Bến xe Miền Đông')
insert into Chuyen values(-43, 31, N'Bến xe Miền Đông')
---43 go
insert into Chuyen values(43, 1, N'Bến xe Miền Đông')
insert into Chuyen values(43, 2, N'Ngã Tư Nguyễn Xí')
insert into Chuyen values(43, 3, N'Ngã Tư Chu Văn An')
insert into Chuyen values(43, 4, N'Cầu Đinh Bộ Lĩnh')
insert into Chuyen values(43, 5, N'Trạm xăng dầu')
insert into Chuyen values(43, 6, N'Chợ Hàng Xanh')
insert into Chuyen values(43, 7, N'Đại học Hutech')
insert into Chuyen values(43, 8, N'Khu Du lịch Văn Thánh')
insert into Chuyen values(43, 9, N'Cầu Sài Gòn')
insert into Chuyen values(43, 10, N'Công viên dạ cầu Sài Gòn')
insert into Chuyen values(43, 11, N'Nhà sách An Bình')
insert into Chuyen values(43, 12, N'KTX Đại học Giao thông Vận tải')
insert into Chuyen values(43, 13, N'Chùa Diệu Giác')
insert into Chuyen values(43, 14, N'Lương Định Của')
insert into Chuyen values(43, 15, N'Trần Não')
insert into Chuyen values(43, 16, N'Đình Bình Khánh')
insert into Chuyen values(43, 17, N'Đường Số 8')
insert into Chuyen values(43, 18, N'Chùa Huệ Nghiêm')
insert into Chuyen values(43, 19, N'Cầu Ông Tranh')
insert into Chuyen values(43, 20, N'Siêu thị Chợ Lớn')
insert into Chuyen values(43, 21, N'Phòng Đào tạo Quận 2')
insert into Chuyen values(43, 22, N'Chùa Thái Nguyên')
insert into Chuyen values(43, 23, N'Trường Cấp 3 Giồng Ông Tố')
insert into Chuyen values(43, 24, N'Trung tâm y tế dự phòng Quận 2')
insert into Chuyen values(43, 25, N'Trung tâm dạy nghề quận 2')
insert into Chuyen values(43, 26, N'Đường số 10')
insert into Chuyen values(43, 27, N'Chợ Cây Xoài')
insert into Chuyen values(43, 28, N'UBND Phường Cát Lái')
insert into Chuyen values(43, 29, N'Khu Dân Cư Phố Đông')
insert into Chuyen values(43, 30, N'Sân bóng đá mini')
insert into Chuyen values(43, 31, N'Trường Hải Quân')
insert into Chuyen values(43, 32, N'Cát Lái')
---53 back
insert into Chuyen values(-53, 1, N'Bến Xe Buýt ÐH Quốc Gia')
insert into Chuyen values(-53, 2, N'KTX Khu B ĐHQG')
insert into Chuyen values(-53, 3, N'Viện Tài nguyên môi trường')
insert into Chuyen values(-53, 4, N'Nhà khách ĐHQG')
insert into Chuyen values(-53, 5, N'Hồ Đá')
insert into Chuyen values(-53, 6, N'Đại học Quốc tế')
insert into Chuyen values(-53, 7, N'Nhà văn hoá sinh viên')
insert into Chuyen values(-53, 8, N'Đại học Khoa học xã hội và Nhân văn')
insert into Chuyen values(-53, 9, N'Khu DL Suối Tiên')
insert into Chuyen values(-53, 10, N'Đại học Nông Lâm')
insert into Chuyen values(-53, 11, N'Công ty Nissan')
insert into Chuyen values(-53, 12, N'Đại học Ngân hàng')
insert into Chuyen values(-53, 13, N'Đầu đường Lê Văn Chí')
insert into Chuyen values(-53, 14, N'Ngã 4 Bình Thái')
insert into Chuyen values(-53, 15, N'Cầu Đen')
insert into Chuyen values(-53, 16, N'Mầm non Hoa Lư')
insert into Chuyen values(-53, 17, N'Bến Bạch Đằng')
insert into Chuyen values(-53, 18, N'Trạm Trung chuyển trên đường Hàm Nghi')
insert into Chuyen values(-53, 19, N'Nguyễn Thị Nghĩa')
insert into Chuyen values(-53, 20, N'Tôn Thất Tùng')
insert into Chuyen values(-53, 21, N'Nhà thờ Huyện Sỹ')
insert into Chuyen values(-53, 22, N'Trung ương Hội Chữ thập đỏ TP')
insert into Chuyen values(-53, 23, N'Nhà sách Minh Khai')
insert into Chuyen values(-53, 24, N'Ngã tư Trần Bình Trọng')
insert into Chuyen values(-53, 25, N'Lê Hồng Phong')
---53 go
insert into Chuyen values(53, 1, N'Lê Hồng Phong')
insert into Chuyen values(53, 2, N'Nhà Sách Minh Khai')
insert into Chuyen values(53, 3, N'Trần Hưng Đạo')
insert into Chuyen values(53, 4, N'Rạp Trần Hưng Đạo')
insert into Chuyen values(53, 5, N'KTX Trần Hưng Đạo')
insert into Chuyen values(53, 6, N'Nguyễn Kim')
insert into Chuyen values(53, 7, N'Trạm Trung chuyển trên đường Hàm Nghi')
insert into Chuyen values(53, 8, N'Bến Bạch Đằng')
insert into Chuyen values(53, 9, N'Nguyễn Hữu Cảnh')
insert into Chuyen values(53, 10, N'Cầu Đen')
insert into Chuyen values(53, 11, N'Khu QLGTDT số 2')
insert into Chuyen values(53, 12, N'Đầu đường Lê Văn Chí')
insert into Chuyen values(53, 13, N'Đại học Ngân hàng')
insert into Chuyen values(53, 14, N'Vietcombank')
insert into Chuyen values(53, 15, N'Cầu Vượt Trạm 2')
insert into Chuyen values(53, 16, N'Suối Tiên')
insert into Chuyen values(53, 17, N'Vành đại ĐHQG TPHCM')
insert into Chuyen values(53, 18, N'Bến xe buýt Khu A ĐHQG')
insert into Chuyen values(53, 19, N'Nhà Văn hoá sinh viên')
insert into Chuyen values(53, 20, N'Đại học Quốc tế')
insert into Chuyen values(53, 21, N'Đại học Quốc tế')
insert into Chuyen values(53, 22, N'Hồ Đá')
insert into Chuyen values(53, 23, N'Nhà Khách ĐHQG')
insert into Chuyen values(53, 24, N'Viện Tài nguyên môi trường')
insert into Chuyen values(53, 25, N'KTX Khu B ĐHQG')
insert into Chuyen values(53, 26, N'Bến Xe Buýt ÐH Quốc Gia')
---55 back
insert into Chuyen values(-55, 1, N'Bến xe Miền Đông mới')
insert into Chuyen values(-55, 2, N'Đường Hoàng Hữu Nam')
insert into Chuyen values(-55, 3, N'Sân Golf')
insert into Chuyen values(-55, 4, N'Học Viện Thanh Thiếu niên Việt Nam')
insert into Chuyen values(-55, 5, N'Cầu Xây')
insert into Chuyen values(-55, 6, N'Đường cầu xây')
insert into Chuyen values(-55, 7, N'Ngã 3 Mỹ Thành')
insert into Chuyen values(-55, 8, N'Ngã ba Mỹ Thành')
insert into Chuyen values(-55, 9, N'Công Ty FILIED')
insert into Chuyen values(-55, 10, N'Chung cư C7')
insert into Chuyen values(-55, 11, N'Đại Học GTVT')
insert into Chuyen values(-55, 12, N'Bệnh viện Quận 9')
insert into Chuyen values(-55, 13, N'Chợ Tăng Nhơn Phú B')
insert into Chuyen values(-55, 14, N'Chợ Hiệp Phú')
insert into Chuyen values(-55, 15, N'Trạm y tế Phường Hiệp Phú')
insert into Chuyen values(-55, 16, N'Nhà sách Thành Nghĩa')
insert into Chuyen values(-55, 17, N'Bệnh viện 7C-Trường Quân y 2')
insert into Chuyen values(-55, 18, N'Siêu thị Coopmart')
insert into Chuyen values(-55, 19, N'Ngã tư Thủ Đức')
insert into Chuyen values(-55, 20, N'Betong Hải Âu')
insert into Chuyen values(-55, 21, N'UBND Quận 9')
insert into Chuyen values(-55, 22, N'Du lịch Công đoàn Quận Thủ Đức')
insert into Chuyen values(-55, 23, N'Ngã 4 Bình Thái')
insert into Chuyen values(-55, 24, N'Công ty truyền tải điện 4')
insert into Chuyen values(-55, 25, N'Ngã 4 Tây Hòa (RMK)')
insert into Chuyen values(-55, 26, N'Xi măng Hà Tiên')
insert into Chuyen values(-55, 27, N'Cát Lái')
insert into Chuyen values(-55, 28, N'Metro Quận 2')
insert into Chuyen values(-55, 29, N'Thảo Điền')
insert into Chuyen values(-55, 30, N'Cầu Đen')
insert into Chuyen values(-55, 31, N'Cầu Sài Gòn')
insert into Chuyen values(-55, 32, N'Khu Du lịch Văn Thánh')
insert into Chuyen values(-55, 33, N'Đại học Hutech')
insert into Chuyen values(-55, 34, N'Cây xăng dầu')
insert into Chuyen values(-55, 35, N'Chợ Hàng Xanh')
insert into Chuyen values(-55, 36, N'Nhà thờ Hàng Xanh')
insert into Chuyen values(-55, 37, N'Chùa Bồ Đề')
insert into Chuyen values(-55, 38, N'Tòa Án nhân dân Quận Bình Thạnh')
insert into Chuyen values(-55, 39, N'Chợ Bà Chiểu')
insert into Chuyen values(-55, 40, N'UBND Quận Bình Thạnh')
insert into Chuyen values(-55, 41, N'Bệnh Viện Gia Định')
insert into Chuyen values(-55, 42, N'PCCC quận Bình Thạnh')
insert into Chuyen values(-55, 43, N'Bệnh viện Phước An')
insert into Chuyen values(-55, 44, N'Đại học Văn Hiến')
insert into Chuyen values(-55, 45, N'Ngã Tư Thích Quảng Đức')
insert into Chuyen values(-55, 46, N'Ngã tư Phan Xích Long')
insert into Chuyen values(-55, 47, N'Ngã tư Phú Nhuận')
insert into Chuyen values(-55, 48, N'Nhà Truyền Thông')
insert into Chuyen values(-55, 49, N'Ngã ba Hồ Văn Huê')
insert into Chuyen values(-55, 50, N'Coop Mart Nguyễn Kiệm')
insert into Chuyen values(-55, 51, N'Chùa Vạn Hạnh')
insert into Chuyen values(-55, 52, N'Trường Cao đẳng Hải Quan')
insert into Chuyen values(-55, 53, N'Cầu vượt Nguyễn Thái Sơn - Nguyễn Kiệm')
insert into Chuyen values(-55, 54, N'Ngã ba Phạm Ngũ Lão')
insert into Chuyen values(-55, 55, N'Cầu vượt ngã sáu Gò Vấp')
insert into Chuyen values(-55, 56, N'Siêu thị Văn Lang')
insert into Chuyen values(-55, 57, N'Công ty 32')
insert into Chuyen values(-55, 58, N'Nhà thờ Xóm Thuốc')
insert into Chuyen values(-55, 59, N'UBND Quận Gò Vấp')
insert into Chuyen values(-55, 60, N'VKSND Quận Gò Vấp')
insert into Chuyen values(-55, 61, N'Chùa Huỳnh Kim')
insert into Chuyen values(-55, 62, N'City Mart')
insert into Chuyen values(-55, 63, N'Chợ Hạnh Thông Tây')
insert into Chuyen values(-55, 64, N'Trường THPT Nguyễn Công Trứ')
insert into Chuyen values(-55, 65, N'Dệt may Phương Đông')
insert into Chuyen values(-55, 66, N'Làng SOS')
insert into Chuyen values(-55, 67, N'Công ty Đồng Tâm')
insert into Chuyen values(-55, 68, N'Ngã tư Cầu cống')
insert into Chuyen values(-55, 69, N'Chợ Cầu')
insert into Chuyen values(-55, 70, N'Chợ Cầu')
insert into Chuyen values(-55, 71, N'Cầu vượt Quang Trung')

---55 go
insert into Chuyen values(55, 1, N'Công viên phần mềm Quang Trung')
insert into Chuyen values(55, 2, N'Công viên Phần mềm Quang Trung')
insert into Chuyen values(55, 3, N'Đông Bắc')
insert into Chuyen values(55, 4, N'Công viên Phần mềm Quang Trung')
insert into Chuyen values(55, 5, N'Cầu vượt Quang Trung')
insert into Chuyen values(55, 6, N'Chợ Cầu')
insert into Chuyen values(55, 7, N'Chợ Cầu')
insert into Chuyen values(55, 8, N'Ngã tư Cầu cống')
insert into Chuyen values(55, 9, N'Công ty Đồng Tâm')
insert into Chuyen values(55, 10, N'Làng SOS')
insert into Chuyen values(55, 11, N'Ngã ba Tân Sơn')
insert into Chuyen values(55, 12, N'Dệt may Phương Đông')
insert into Chuyen values(55, 13, N'Trường THPT Nguyễn Công Trứ')
insert into Chuyen values(55, 14, N'Chợ Hạnh Thông Tây')
insert into Chuyen values(55, 15, N'City Mart')
insert into Chuyen values(55, 16, N'Chùa Huỳnh Kim')
insert into Chuyen values(55, 17, N'VKSND Quận Gò Vấp')
insert into Chuyen values(55, 18, N'UBND Quận Gò Vấp')
insert into Chuyen values(55, 19, N'Nhà Thờ Xóm Thuốc')
insert into Chuyen values(55, 20, N'Xóm thuốc')
insert into Chuyen values(55, 21, N'Công ty 32')
insert into Chuyen values(55, 22, N'Siêu thị Văn Lang')
insert into Chuyen values(55, 23, N'Cầu vượt ngã sáu Gò Vấp')
insert into Chuyen values(55, 24, N'Bệnh Viện 175')
insert into Chuyen values(55, 25, N'Chợ Tân Sơn Nhất')
insert into Chuyen values(55, 26, N'Đầu công viên Gia Định')
insert into Chuyen values(55, 27, N'Cuối công viên Gia Định')
insert into Chuyen values(55, 28, N'Đầu Đường Đào Duy Anh')
insert into Chuyen values(55, 29, N'Cuối Đường Đào Duy Anh')
insert into Chuyen values(55, 30, N'Ngã ba Đào Duy Anh')
insert into Chuyen values(55, 31, N'Tháp Nước')
insert into Chuyen values(55, 32, N'Trung tâm hội nghị tiệc cưới White Palace')
insert into Chuyen values(55, 33, N'Ngã tư Phú Nhuận')
insert into Chuyen values(55, 34, N'Ngã tư Phan Xích Long')
insert into Chuyen values(55, 35, N'Ngã Tư Thích Quảng Đức')
insert into Chuyen values(55, 36, N'Trường Đại học Văn Hiến')
insert into Chuyen values(55, 37, N'Bệnh Viện Phước An')
insert into Chuyen values(55, 38, N'Công viên Văn hóa Phú Nhuận')
insert into Chuyen values(55, 39, N'UBND Quận Bình Thạnh')
insert into Chuyen values(55, 40, N'Lăng Ông Bà Chiểu')
insert into Chuyen values(55, 41, N'Chợ Bà Chiểu')
insert into Chuyen values(55, 42, N'Tòa Án nhân dân Quận Bình Thạnh')
insert into Chuyen values(55, 43, N'Chùa Bồ Đề')
insert into Chuyen values(55, 44, N'Nhà thờ Hàng Xanh')
insert into Chuyen values(55, 45, N'Chợ Hàng Xanh')
insert into Chuyen values(55, 46, N'Đại học Hutech')
insert into Chuyen values(55, 47, N'Khu Du lịch Văn Thánh')
insert into Chuyen values(55, 48, N'Cầu Sài Gòn')
insert into Chuyen values(55, 49, N'Cầu Đen')
insert into Chuyen values(55, 50, N'Thảo Điền')
insert into Chuyen values(55, 51, N'Metro Quận 2')
insert into Chuyen values(55, 52, N'Cát Lái')
insert into Chuyen values(55, 53, N'Xi măng hà tiên - trạm thu phí')
insert into Chuyen values(55, 54, N'Ngã 4 Tây Hòa (RMK)')
insert into Chuyen values(55, 55, N'Trạm xây dựng')
insert into Chuyen values(55, 56, N'Khu QLGTDT số 2')
insert into Chuyen values(55, 57, N'Ngã 4 Bình Thái')
insert into Chuyen values(55, 58, N'UBND quận 9')
insert into Chuyen values(55, 59, N'Bê tông Hải Âu')
insert into Chuyen values(55, 60, N'Ngã 4 Thủ Đức')
insert into Chuyen values(55, 61, N'Siêu thị Coopmart')
insert into Chuyen values(55, 62, N'Bệnh viện 7C-Trường Quân y 2')
insert into Chuyen values(55, 63, N'Nhà sách Thành Nghĩa')
insert into Chuyen values(55, 64, N'Trạm y tế Phường Hiệp Phú')
insert into Chuyen values(55, 65, N'Chợ Hiệp Phú')
insert into Chuyen values(55, 66, N'Chợ Tăng Nhơn Phú')
insert into Chuyen values(55, 67, N'Bệnh viện Quận 9')
insert into Chuyen values(55, 68, N'Đại Học GTVT')
insert into Chuyen values(55, 69, N'Chung cư C7')
insert into Chuyen values(55, 70, N'Công Ty FILIED')
insert into Chuyen values(55, 71, N'Ngã ba Mỹ Thành')
insert into Chuyen values(55, 72, N'Ngã 3 Mỹ Thành')
insert into Chuyen values(55, 73, N'Đường cầu xây')
insert into Chuyen values(55, 74, N'Cầu Xây')
insert into Chuyen values(55, 75, N'Học viện Thanh Thiếu niên Việt Nam')
---88 back
insert into Chuyen values(-88, 1, N'Chợ Long Phước')
insert into Chuyen values(-88, 2, N'Nhà bia tưởng niệm')
insert into Chuyen values(-88, 3, N'Ngã 3 Long Phước')
insert into Chuyen values(-88, 4, N'Trại nhím')
insert into Chuyen values(-88, 5, N'phim trường')
insert into Chuyen values(-88, 6, N'Cầu Trường Phước')
insert into Chuyen values(-88, 7, N'Ngã ba Long Thuận')
insert into Chuyen values(-88, 8, N'Cầu Võ Khế')
insert into Chuyen values(-88, 9, N'Trạm y tế')
insert into Chuyen values(-88, 10, N'Ngã 3 Tam Đa')
insert into Chuyen values(-88, 11, N'Chợ Long Trường')
insert into Chuyen values(-88, 12, N'UBND phường Long Trường')
insert into Chuyen values(-88, 13, N'Đường Số 6')
insert into Chuyen values(-88, 14, N'Trường Long Trường')
insert into Chuyen values(-88, 15, N'Đường Số 1')
insert into Chuyen values(-88, 16, N'Cao Tốc Dầu Giây')
insert into Chuyen values(-88, 17, N'Cầu Huyện Thanh')
insert into Chuyen values(-88, 18, N'Nhà Thờ Phú Hữu')
insert into Chuyen values(-88, 19, N'UBND P.Phú Hữu')
insert into Chuyen values(-88, 20, N'Trường Hoa Hồng Đỏ')
insert into Chuyen values(-88, 21, N'vành đai trong')
insert into Chuyen values(-88, 22, N'Cầu xây dựng')
insert into Chuyen values(-88, 23, N'Công ty Thành Công')
insert into Chuyen values(-88, 24, N'Ngã 3 Đỗ Xuân Hợp')
insert into Chuyen values(-88, 25, N'Đỗ Xuân Hợp')
insert into Chuyen values(-88, 26, N'Trường Nguyễn Văn Trỗi')
insert into Chuyen values(-88, 27, N'Đường số 6')
insert into Chuyen values(-88, 28, N'Nhà Sách Nguyễn Văn Cừ')
insert into Chuyen values(-88, 29, N'Lê Văn Thịnh')
insert into Chuyen values(-88, 30, N'Công ty Bình An')
insert into Chuyen values(-88, 31, N'Nhà thiếu nhi Quận 2')
insert into Chuyen values(-88, 32, N'Trường Giồng Ông Tố')
insert into Chuyen values(-88, 33, N'Phòng Đào tạo Quận 2')
insert into Chuyen values(-88, 34, N'Siêu thị Chợ Lớn')
insert into Chuyen values(-88, 35, N'Cầu Ông Tranh')
insert into Chuyen values(-88, 36, N'Chùa Huệ Nghiêm')
insert into Chuyen values(-88, 37, N'Đường số 8')
insert into Chuyen values(-88, 38, N'Đình Bình Khánh')
insert into Chuyen values(-88, 39, N'Trần Não')
insert into Chuyen values(-88, 40, N'Hồ Bơi Hải Quân')
insert into Chuyen values(-88, 41, N'Mầm non Hoa Lư')
insert into Chuyen values(-88, 42, N'Ngô Văn Năm')
insert into Chuyen values(-88, 43, N'Bến Bạch Đằng')
insert into Chuyen values(-88, 44, N'Cục Hải Quan Thành Phố')
insert into Chuyen values(-88, 45, N'Chợ Cũ')
insert into Chuyen values(-88, 46, N'Trường Cao Thắng')
insert into Chuyen values(-88, 47, N'Trạm Trung chuyển trên đường Hàm Nghi')
insert into Chuyen values(-88, 48, N'Khách sạn New World')
insert into Chuyen values(-88, 49, N'Nguyễn Thị Nghĩa')
insert into Chuyen values(-88, 50, N'Tôn Thất Tùng')
insert into Chuyen values(-88, 51, N'Bến xe buýt Sài Gòn')
---88 go
insert into Chuyen values(88, 1, N'Bến xe buýt Sài Gòn')
insert into Chuyen values(88, 2, N'Tôn Thất Tùng')
insert into Chuyen values(88, 3, N'KTX Trần Hưng Đạo')
insert into Chuyen values(88, 4, N'Nguyễn Kim')
insert into Chuyen values(88, 5, N'Trạm Trung chuyển trên đường Hàm Nghi')
insert into Chuyen values(88, 6, N'Nam Kỳ Khởi Nghĩa')
insert into Chuyen values(88, 7, N'Chợ Cũ')
insert into Chuyen values(88, 8, N'Hồ Tùng Mậu')
insert into Chuyen values(88, 9, N'Bến Bạch Đằng')
insert into Chuyen values(88, 10, N'Bảo tàng Tôn Đức Thắng')
insert into Chuyen values(88, 11, N'Ngô Văn Năm')
insert into Chuyen values(88, 12, N'Ba Son')
insert into Chuyen values(88, 13, N'Nguyễn Hữu Cảnh')
insert into Chuyen values(88, 14, N'Mầm non Hoa Lư')
insert into Chuyen values(88, 15, N'Hồ Bơi Hải Quân')
insert into Chuyen values(88, 16, N'Trần Não')
insert into Chuyen values(88, 17, N'Đình Bình Khánh')
insert into Chuyen values(88, 18, N'Đường Số 8')
insert into Chuyen values(88, 19, N'Chùa Huệ Nghiêm')
insert into Chuyen values(88, 20, N'Cầu Ông Tranh')
insert into Chuyen values(88, 21, N'Siêu thị Chợ Lớn')
insert into Chuyen values(88, 22, N'Phòng Đào tạo Quận 2')
insert into Chuyen values(88, 23, N'Trường Giồng Ông tố')
insert into Chuyen values(88, 24, N'Nhà thiếu nhi Quận 2')
insert into Chuyen values(88, 25, N'Công ty Bình An')
insert into Chuyen values(88, 26, N'Lê Văn Thịnh')
insert into Chuyen values(88, 27, N'Nhà Sách Nguyễn Văn Cừ')
insert into Chuyen values(88, 28, N'Đường số 6')
insert into Chuyen values(88, 29, N'Trường Nguyễn Văn Trỗi')
insert into Chuyen values(88, 30, N'Đỗ Xuân Hợp')
insert into Chuyen values(88, 31, N'Ngã 3 Đỗ Xuân Hợp')
insert into Chuyen values(88, 32, N'Công ty Thành Công')
insert into Chuyen values(88, 33, N'cầu Xây Dựng')
insert into Chuyen values(88, 34, N'Vành đai trong')
insert into Chuyen values(88, 35, N'Trường Hoa Hồng Đỏ')
insert into Chuyen values(88, 36, N'UBND P.Phú Hữu')
insert into Chuyen values(88, 37, N'Nhà Thờ Phú Hữu')
insert into Chuyen values(88, 38, N'Cầu Huyện Thanh')
insert into Chuyen values(88, 39, N'Cao Tốc Dầu Giây')
insert into Chuyen values(88, 40, N'Đường Số 1')
insert into Chuyen values(88, 41, N'Trường Long Trường')
insert into Chuyen values(88, 42, N'Đường Số 6')
insert into Chuyen values(88, 43, N'UBND phường Long Trường')
insert into Chuyen values(88, 44, N'Chợ Long Trường')
insert into Chuyen values(88, 45, N'Ngã ba Tam Đa')
insert into Chuyen values(88, 46, N'Trạm y tế')
insert into Chuyen values(88, 47, N'Cầu Võ Khế')
insert into Chuyen values(88, 48, N'Ngã ba Long Thuận')
insert into Chuyen values(88, 49, N'Cầu Trường Phước')
insert into Chuyen values(88, 50, N'phim trường')
insert into Chuyen values(88, 51, N'Trại nhím')
insert into Chuyen values(88, 52, N'Ngã ba Long Phước')
insert into Chuyen values(88, 53, N'Trường tiểu học Long Phước')
insert into Chuyen values(88, 54, N'Chợ Long Phước')
*/